## A Single Neuron:

  * The following code is the step by step exercise of how to create a Neuron Network to understand the process and logic behind it.

In [ ]:
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

In [ ]:
output = (inputs[0]*weights[0] +
          inputs[1]*weights[1] +
          inputs[2]*weights[2] + bias)
print(output)

2.3


In [ ]:
inputs_2 = [1.0, 2.0, 3.0, 2.5]
weights_2 = [0.2, 0.8, -0.5, 1.0]
bias_2 = 2.0

In [ ]:
output_2 = (inputs_2[0]*weights_2[0] +
           inputs_2[1]*weights_2[1] +
           inputs_2[2]*weights_2[2] +
           inputs_2[3]*weights_2[3] + bias_2)
print(output2)

4.8


## A Layer of Neurons

 * Neural networks typically have layers compose of several neurons. Layers are nothing more than groups of neurons and each one of them takes the same input(training data or output from the previous layer), but contains its own set of weights and bias, producing its own unique output.

In [ ]:
inputs = [1, 2, 3, 2.5]

weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

In [ ]:
outputs = [
        # Neuron 1:
        inputs[0]*weights1[0] +
        inputs[1]*weights1[1] +
        inputs[2]*weights1[2] +
        inputs[3]*weights1[3] + bias1,

        # Neuron 2:
        inputs[0]*weights2[0] +
        inputs[1]*weights2[1] +
        inputs[2]*weights2[2] +
        inputs[3]*weights2[3] + bias2,

        # Neuron 3:
        inputs[0]*weights3[0] +
        inputs[1]*weights3[1] +
        inputs[2]*weights3[2] +
        inputs[3]*weights3[3] + bias3
]

print(outputs)

[4.8, 1.21, 2.385]


The previous code with 3 sets of weights and biases that defined three neurons, are called a fully connected neural network (every neuron in the layer has connections to every neuron from the previous layer, a common case but not a requirement).

The problem with hard-coding the neurons like the previous one happens when one wants to escalate the network, for that a loop is needed.

In [ ]:
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

In [ ]:
# Output of current layer
layer_outputs = []
# For each neuron
for neuron_weights, neuron_bias in zip(weights, biases):
    # Zeroed output of given neuron
    neuron_output = 0
    # For each input and weight to the neuron
    for n_input, weight in zip(inputs, neuron_weights):
      # Multiply this input by associated weight
      # and add to the neuron's output variable
      neuron_output += n_input*weight
    # Add bias
    neuron_output += neuron_bias
    # Put neuron's result to the layer's output list
    layer_outputs.append(neuron_output)

print(layer_outputs)

[4.8, 1.21, 2.385]


## A Single Neuron with NumPy

  * Now that a single neuron has been hardcoded, a new one will be made but using the dot product and the addition of the vectors with NumPy. This makes the code much simpler to read and write (and faster to run):

In [ ]:
import numpy as np

input = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

outputs = np.dot(weights, inputs) + bias

print(outputs)

4.8


## A Layer of Neurons with NumPy

In [ ]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

In [ ]:
layer_outputs = np.dot(weights, inputs) + biases

print(layer_outputs)

[4.8   1.21  2.385]


## A Batch of Data

### Data Manipulation

In [1]:
import numpy as np

a = [1, 2, 3]
b = [2, 3, 4]

a = np.array([a])
b = np.array([b]).T

In [2]:
print(np.dot(a,b))

[[20]]


## A Layer of Neurons & Batch of Data w/ NumPy

In [3]:
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

outputs = np.dot(inputs, np.array(weights).T) + biases

In [5]:
np.dot(inputs, np.array(weights).T) #result without biases

array([[ 2.8  , -1.79 ,  1.885],
       [ 6.9  , -4.81 , -0.3  ],
       [-0.59 , -1.949, -0.474]])

In [6]:
print(outputs) # result with the biases added to each neuron

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
